### ISSUE TITLE
Finna leiða til þess að vinna úr gögnum. Hvernig ætlum við að fara að því?

### ISSUE THREAD

**Issue by KetillG** [sindrip/Lokaverkefni-vefforitun#5]

**Comment by sindrip** [comment]
Dæmi um unnar upplýsingar úr loggum sem lesarinn minn skilar, skrifa parser sem færir þetta yfir í lesanlegt form (typecast) og vistar í array undir object nöfnum eins og t.d. date, gametime, loadtime o.s.frv.

Wed Jan 15 2014 22:45:29 GMT+0000 (Greenwich Standard Time)
1
:
"000022.709|  765968.0000kb|    748.0000kb added| ALWAYS| Spawning champion (Nocturne) with skinID 4 on team 200 for clientID 9 and summonername (LucianStoleMyTv) (is HUMAN PLAYER)
"
2
:
"000023.301|  781252.0968kb|    964.0000kb added| ALWAYS| Spawning champion (Orianna) with skinID 0 on team 100 for clientID 2 and summonername (Przybor) (is HUMAN PLAYER)
"
3
:
"000023.617|  785044.0968kb|   5708.0000kb added| ALWAYS| Spawning champion (Ezreal) with skinID 0 on team 100 for clientID 0 and summonername (BaRi) (is HUMAN PLAYER)
"
4
:
"000023.864|  796684.0032kb|      8.0000kb added| ALWAYS| Spawning champion (Nidalee) with skinID 5 on team 100 for clientID 8 and summonername (Kepczyk) (is HUMAN PLAYER)
"
5
:
"000023.875|  797276.0032kb|    592.0000kb added| ALWAYS| Spawning champion (Swain) with skinID 3 on team 100 for clientID 1 and summonername (zolty) (is HUMAN PLAYER)
"
6
:
"000023.880|  797324.0032kb|     28.0000kb added| ALWAYS| Spawning champion (Elise) with skinID 0 on team 100 for clientID 3 and summonername (Bisingir) (is HUMAN PLAYER)
"
7
:
"000023.895|  797784.0000kb|    460.0000kb added| ALWAYS| Spawning champion (Morgana) with skinID 0 on team 200 for clientID 6 and summonername (Dopey Yorle) (is HUMAN PLAYER)
"
8
:
"000023.921|  797776.0000kb|      4.0000kb added| ALWAYS| Spawning champion (TwistedFate) with skinID 7 on team 200 for clientID 7 and summonername (Scaredy Yordle) (is HUMAN PLAYER)
"
9
:
"000023.922|  797776.0000kb|      0.0000kb added| ALWAYS| Spawning champion (Ezreal) with skinID 1 on team 200 for clientID 5 and summonername (King Yordle) (is HUMAN PLAYER)
"
10
:
"000023.930|  798036.0968kb|    260.0000kb added| ALWAYS| Spawning champion (Shen) with skinID 5 on team 200 for clientID 4 and summonername (Don Yordle) (is HUMAN PLAYER)
"
11
:
"000026.764|  869984.0000kb|    688.0000kb added| ALWAYS| GAMESTATE_GAMELOOP Begin
"
12
:
"000221.903| 1317432.0064kb|      8.0000kb added| ALWAYS| The Killer was: Bisingir
"
13
:
"000336.591| 1342328.0064kb|      0.0000kb added| ALWAYS| The Killer was: Kepczyk
"
14
:
"000526.803| 1355984.0000kb|      0.0000kb added| ALWAYS| The Killer was: zolty
"
15
:
"000613.749| 1358780.0032kb|      0.0000kb added| ALWAYS| The Killer was: BaRi
"
16
:
"000955.761|  765896.0000kb|      0.0000kb added| ALWAYS| {"messageType":"riot__game_client__connection_info","message_body":"Game exited","exit_code":"EXITCODE_WIN"}
"
length
:
17
