### ISSUE TITLE
Búa til forrit sem les inn alla file-a úr möppu

### ISSUE THREAD

**Issue by KetillG** [sindrip/Lokaverkefni-vefforitun#6]

**Comment by KetillG** [comment]
Hugmynd1: 
a) Notandi velur alla file-a sem viljum nota.
b) Sendum 1 file í einu niður í fall sem hendir burt öllum línum sem innihalda ekki gögn sem viljum nota.(Myndum þá skilgreina textKey sem innihéldi listi yfir öll lykilorð sem viljum finna.)
Hendir gögnunum sem fundust í fylki?
c) Sendum styttu skránna/fylkið niður í annað fall sem vinnur úr gögnunum sem fundust og setur í yfirfylkið.

Hugmynd2:
a) Notandi velur alla file-a sem viljum nota.
b) Sendum 1 file í einu niður í fall sem hendir burt öllum línum sem innihalda ekki gögn sem viljum nota.(Myndum þá skilgreina textKey sem innihéldi listi yfir öll lykilorð sem viljum finna.)
c) Fyrir hverja línu sem finnst er kallað á sér handler fyrir þá línu.

**Comment by KetillG** [comment]
Held að hugmynd 1 sé sterkari en hugmynd 2. Því gögnin breytast smá á milli ára. Þó að þau geymi sömu gögn þá eru þau sett aðeins öðruvísi fram eins og sjá má á mynd fyrir neðan.

![sindri 2](https://cloud.githubusercontent.com/assets/18271523/19661186/422f8adc-9a22-11e6-968c-02439bbe5662.png)

Ef unnið væri úr gögnum fyrir hverja línu sem fyndist þá þyrfti að gera if setningu fyrir hverja línu af gögnum í stað þess að gera bara eitt kall sem kallar á viðeigandi parser. Sjá útskýringarmynd fyrir neðan.

![sindri](https://cloud.githubusercontent.com/assets/18271523/19661130/0c30a952-9a22-11e6-99ea-2caf2e99af05.png)

**Comment by sindrip** [comment]
Skiptir ekki máli í hvaða dálki það er, ég þarf bara að vita hvar staðsetningin á því er og veit þá relative staðsetningu gagna sem ég leita að. Eins fyrir gameloop þarf ég bara að vita að það kom fyrir í línunni og kemur einungis einu sinni fyrir í gögnunum.

![image](https://cloud.githubusercontent.com/assets/15222674/19661284/a856dd9c-9a22-11e6-8ad0-e70d507cecb8.png)

**Comment by KetillG** [comment]
Hérna er mynd af því hvernig ég held að við ættum að vinna úr file-unum í augnablikinu. Endilega komið með athugasemdir:

![qqdwqwqdq](https://cloud.githubusercontent.com/assets/18271523/19703809/ba22e1c4-9af4-11e6-8118-8471daf24037.png)

Hérna er linkur á þetta þar sem þið getið editað (ekki viss hvort þetta virkar): https://www.draw.io/#LPLoL

**Comment by KetillG** [comment]
Byrjum á að skipta upp í fylki við nýja línu.
Næst lesum við inn línu fyrir línu.
- Leitum að "Log started at Fri Sep 28 16:38:15 2012"
- Leitum að "GameClock LockToSystemClock time: 0.000000 diff: 0.570290"
- Leitum að ÖLLUM tilvikum af "Spawning champion (Thresh) with skinID 0 on team 100 for clientID 4 and summonername (JimmyAndy BOY) (is HUMAN PLAYER)"
- Leitum að "GAMESTATE_GAMELOOP Begin"
- Leitum að ÖLLUM tilvikum af "000742.946| ALWAYS| The Killer was: LOVE WXR FOREVER"
- Leitum að ","exit_code":"EXITCODE_WIN"}"
