### ISSUE TITLE
Hvernig ætlum við að setja gögn fram?

### ISSUE THREAD

**Issue by KetillG** [sindrip/Lokaverkefni-vefforitun#7]

**Comment by BjornGudmundsson** [comment]
Sýna hversu mikið þú hefur spilað sem fall af tima, t.d. hversu mikið þu spilar sem fall af degi.

**Comment by KetillG** [comment]
Fann þetta interactive graf, ættum að reyna útfæra, og nota kannski d3 shittið við gerð vefsins. Virðist auðvelda marga hluti.
